# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - 3.3
matrix:
  include:
    - python: 2.7
      env:
        - TESTMODE=full
        - COVERAGE=--coverage
    - python: 2.6
      env:
        - TESTMODE=fast
        - OPTIMIZE=-OO
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - mkdir builds
  - pushd builds
  - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors nose numpy Cython mpmath argparse
  - if [ "${TESTMODE}" == "full" ]; then pip install coverage coveralls; fi
  - python -V
  - popd
script:
  - python $OPTIMIZE runtests.py -g -m $TESTMODE $COVERAGE
env:
  - TESTMODE=fast
notifications:
  # Perhaps we should have status emails sent to the mailing list, but
  # let's wait to see what people think before turning that on.
  email: false
after_success:
    - if [ "${TESTMODE}" == "full" ]; then cp build/test/.coverage . && coveralls; fi
